package it.unibo.trace.data.supabase.entities

import kotlinx.serialization.Serializable

/**
 * Data class representing a Todo item in the database.
 * 
 * @property id The unique identifier for the todo (auto-generated by the database).
 * @property name The descriptive name or title of the task.
 * @property uid The unique identifier of the user who owns this task.
 */
@Serializable
data class TodoItem(
    val id: Long? = null,
    val name: String,
    val uid: String? = null
)
